### ISSUE TITLE
tbep0122 ref displays incorrectly

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/tbnmc-compliance-assessment-2021#2]
2021 WQ assessment reference not coded correctly, just shows up as ????
https://github.com/tbep-tech/tbnmc-compliance-assessment-2021/blob/90b1bb2e596ff488616554b724e1a3915b8b6348/index.Rmd#L217

**Comment by fawda123** [comment]
Done, I had to add the reference to the bibs.bib file.
